"""initial schema

Revision ID: 965bad48ea27
Revises: 
Create Date: 2026-09-09 22:09:21.387289
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '965bad48ea27'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('credentials', sa.LargeBinary(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_integrations_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('org_id', 'provider', 'display_name', name=op.f('uq_integrations_org_id_provider_display_name'))
    )
    op.create_index(op.f('ix_integrations_org_id'), 'integrations', ['org_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_jobs_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('kind', 'dedupe_key', name=op.f('uq_jobs_kind_dedupe_key'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_teams_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('org_id', 'slug', name=op.f('uq_teams_org_id_slug'))
    )
    op.create_index(op.f('ix_teams_org_id'), 'teams', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('org_id', 'email', name=op.f('uq_users_org_id_email'))
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('deploys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('repo_full_name', sa.String(length=300), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('environment', sa.String(length=100), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=True),
    sa.Column('ref', sa.String(length=300), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_external_id', sa.String(length=200), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), nullable=False),
    sa.Column('reverts_sha', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_deploys_actor_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_deploys_integration_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_deploys_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_deploys_team_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deploys')),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name=op.f('uq_deploys_org_id_provider_external_id'))
    )
    op.create_index(op.f('ix_deploys_org_id'), 'deploys', ['org_id'], unique=False)
    op.create_index('ix_deploys_org_team_deployed', 'deploys', ['org_id', 'team_id', 'deployed_at'], unique=False)
    op.create_table('external_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('external_handle', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_external_identities_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities')),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name=op.f('uq_external_identities_org_id_provider_external_id'))
    )
    op.create_index(op.f('ix_external_identities_org_id'), 'external_identities', ['org_id'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('service_external_id', sa.String(length=200), nullable=True),
    sa.Column('service_name', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at_ext', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_incidents_integration_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_incidents_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_incidents_team_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name=op.f('uq_incidents_org_id_provider_external_id'))
    )
    op.create_index(op.f('ix_incidents_org_id'), 'incidents', ['org_id'], unique=False)
    op.create_index('ix_incidents_org_team_created', 'incidents', ['org_id', 'team_id', 'created_at_ext'], unique=False)
    op.create_table('metric_rollups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('grain', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_metric_rollups_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_metric_rollups_team_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_metric_rollups_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_rollups')),
    sa.UniqueConstraint('org_id', 'team_id', 'user_id', 'grain', 'period_start', 'metric_key', name=op.f('uq_metric_rollups_org_id_team_id_user_id_grain_period_start_metric_key'), postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_metric_rollups_lookup', 'metric_rollups', ['org_id', 'team_id', 'metric_key', 'period_start'], unique=False)
    op.create_index(op.f('ix_metric_rollups_org_id'), 'metric_rollups', ['org_id'], unique=False)
    op.create_table('on_call_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('schedule_external_id', sa.String(length=200), nullable=True),
    sa.Column('schedule_name', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_user_id', sa.String(length=200), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_on_call_shifts_integration_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_on_call_shifts_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_on_call_shifts_team_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_on_call_shifts_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_on_call_shifts')),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name=op.f('uq_on_call_shifts_org_id_provider_external_id'))
    )
    op.create_index(op.f('ix_on_call_shifts_org_id'), 'on_call_shifts', ['org_id'], unique=False)
    op.create_index('ix_on_call_shifts_org_user_window', 'on_call_shifts', ['org_id', 'user_id', 'starts_at', 'ends_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('watermark', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], name=op.f('fk_sync_runs_integration_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_integration_id'), 'sync_runs', ['integration_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id', name=op.f('pk_team_members'))
    )
    op.create_table('team_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_team_resources_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_resources_team_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_resources')),
    sa.UniqueConstraint('org_id', 'provider', 'resource_type', 'external_id', name=op.f('uq_team_resources_org_id_provider_resource_type_external_id'))
    )
    op.create_index(op.f('ix_team_resources_org_id'), 'team_resources', ['org_id'], unique=False)
    op.create_index(op.f('ix_team_resources_team_id'), 'team_resources', ['team_id'], unique=False)
    op.create_table('incident_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_user_id', sa.String(length=200), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('paged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('is_ack', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_pages_incident_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_incident_pages_org_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_incident_pages_team_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incident_pages_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_pages')),
    sa.UniqueConstraint('org_id', 'provider', 'external_id', name=op.f('uq_incident_pages_org_id_provider_external_id'))
    )
    op.create_index(op.f('ix_incident_pages_incident_id'), 'incident_pages', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_pages_org_id'), 'incident_pages', ['org_id'], unique=False)
    op.create_index('ix_incident_pages_org_user_paged', 'incident_pages', ['org_id', 'user_id', 'paged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_pages_org_user_paged', table_name='incident_pages')
    op.drop_index(op.f('ix_incident_pages_org_id'), table_name='incident_pages')
    op.drop_index(op.f('ix_incident_pages_incident_id'), table_name='incident_pages')
    op.drop_table('incident_pages')
    op.drop_index(op.f('ix_team_resources_team_id'), table_name='team_resources')
    op.drop_index(op.f('ix_team_resources_org_id'), table_name='team_resources')
    op.drop_table('team_resources')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_sync_runs_integration_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_on_call_shifts_org_user_window', table_name='on_call_shifts')
    op.drop_index(op.f('ix_on_call_shifts_org_id'), table_name='on_call_shifts')
    op.drop_table('on_call_shifts')
    op.drop_index(op.f('ix_metric_rollups_org_id'), table_name='metric_rollups')
    op.drop_index('ix_metric_rollups_lookup', table_name='metric_rollups')
    op.drop_table('metric_rollups')
    op.drop_index('ix_incidents_org_team_created', table_name='incidents')
    op.drop_index(op.f('ix_incidents_org_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_org_id'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index('ix_deploys_org_team_deployed', table_name='deploys')
    op.drop_index(op.f('ix_deploys_org_id'), table_name='deploys')
    op.drop_table('deploys')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_org_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_integrations_org_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
